export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_TODAY = 'GET_EVENTS_TODAY';
export const GET_EVENTS_UPCOMING = 'GET_EVENTS_UPCOMING';
export const GET_USER = 'GET_USER';
export const GET_FAVORITE = 'GET_FAVORITE';
export const POST_FAVORITE = 'POST_FAVORITE';
